//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFrmEF_DBFirst.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumberTbl
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int CategoryId { get; set; }
        public int LocationId { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual CategoryTbl CategoryTbl { get; set; }
        public virtual LocationTbl LocationTbl { get; set; }
        public virtual PersonTbl PersonTbl { get; set; }
    }
}
